# Generated by Django 5.0.4 on 2024-05-17 07:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tracking",
            old_name="tarcking",
            new_name="trcking",
        ),
    ]
