# Generated by Django 5.0.4 on 2024-05-17 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0002_rename_tarcking_tracking_trcking"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tracking",
            old_name="trcking",
            new_name="Tracking",
        ),
    ]
